name:                mfoppl
version:             0.1.0.0
github:              esennesh/mfoppl
license:             BSD3
author:              Eli Sennesh
maintainer:          esennesh@ccs.neu.edu
copyright:           2023 Eli Sennesh

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/esennesh/mfoppl#readme>

dependencies:
- base >= 4.11 && < 10
- containers
- freer-simple
- rio >= 0.1.12.0
- random
- statistics

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mfoppl-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - mfoppl
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  mfoppl-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - mfoppl
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
